package fields

import (
	"github.com/bihari123/beirbal/pipeline/utils"
)

var USDriverLicenseLabel = "PII_US_DRIVER_LICENSE"

type USDriverLicenceEntry = utils.ProdigyOutput

var sampleTextUSDriverLicense = []string{
	"DL %v",
	"DLS %v",
	"CDL %v",
	"CDLS %v",
	"ID %v",
	"IDs %v",
	"DL# %v",
	"DLS# %v",
	"CDL# %v",
	"CDLS# %v",
	"ID# %v",
	"IDs# %v",
	"ID number %v",
	"ID numbers %v",
	"LIC %v",
	"LIC# %v",
	"DLN %v",
	"Keyword_us_drivers_license %v",
	"DriverLic %v",
	"DriverLics %v",
	"DriverLicense %v",
	"DriverLicenses %v",
	"Driver Lic %v",
	"Driver Lics %v",
	"Driver License %v",
	"Driver Licenses %v",
	"DriversLic %v",
	"DriversLics %v",
	"DriversLicense %v",
	"DriversLicenses %v",
	"Drivers Lic %v",
	"Drivers Lics %v",
	"Drivers License %v",
	"Drivers Licenses %v",
	"Driver'Lic %v",
	"Driver'Lics %v",
	"Driver'License %v",
	"Driver'Licenses %v",
	"Driver' Lic %v",
	"Driver' Lics %v",
	"Driver' License %v",
	"Driver' Licenses %v",
	"Driver'sLic %v",
	"Driver'sLics %v",
	"Driver'sLicense %v",
	"Driver'sLicenses %v",
	"Driver's Lic %v",
	"Driver's Lics %v",
	"Driver's License %v",
	"Driver's Licenses %v",
	"identification number %v",
	"identification numbers %v",
	"identification # %v",
	"id card %v",
	"id cards %v",
	"identification card %v",
	"identification cards %v",
	"DriverLic# %v",
	"DriverLics# %v",
	"DriverLicense# %v",
	"DriverLicenses# %v",
	"Driver Lic# %v",
	"Driver Lics# %v",
	"Driver License# %v",
	"Driver Licenses# %v",
	"DriversLic# %v",
	"DriversLics# %v",
	"DriversLicense# %v",
	"DriversLicenses# %v",
	"Drivers Lic# %v",
	"Drivers Lics# %v",
	"Drivers License# %v",
	"Drivers Licenses# %v",
	"Driver'Lic# %v",
	"Driver'Lics# %v",
	"Driver'License# %v",
	"Driver'Licenses# %v",
	"Driver' Lic# %v",
	"Driver' Lics# %v",
	"Driver' License# %v",
	"Driver' Licenses# %v",
	"Driver'sLic# %v",
	"Driver'sLics# %v",
	"Driver'sLicense# %v",
	"Driver'sLicenses# %v",
	"Driver's Lic# %v",
	"Driver's Lics# %v",
	"Driver's License# %v",
	"Driver's Licenses# %v",
	"id card# %v",
	"id cards# %v",
	"identification card# %v",
	"identification cards# %v",
}

var training_statements_driver_license = utils.GenTrainingStatement(
	sampleTextUSDriverLicense,
	USDriverLicenseLabel,
)

func GetTextForFieldUsDriverLicence(us_driver_licence string) USDriverLicenceEntry {
	return utils.GetRandomEntry(training_statements_driver_license, us_driver_licence)
}
